add dynamic prover tests for each framework

diff --git a/framework/Makefile b/framework/Makefile
--- a/framework/Makefile
+++ b/framework/Makefile
@@ -1,12 +1,16 @@
-# Prover Tests are WIP
-# These are the prover tests that have been written
-# and are known to pass
-PROVER_TESTS = demo ol_account slow sacred
-
-VENDOR_TESTS = chain_id guid
 
 prove:
-	@cd libra-framework && \
-	for i in ${PROVER_TESTS} ${VENDOR_TESTS}; do \
-			diem move prove -f $$i; \
-	done
+    @cd move-stdlib && \
+    echo "Testing move-stdlib" && \
+    find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
+    xargs -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+
+    @cd vendor-stdlib && \
+    echo "Testing vendor-stdlib" && \
+    find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
+    xargs -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+
+    @cd libra-framework && \
+    echo "Testing libra-framework" && \
+    find . -type f -name "*.move" ! -name "*.spec.move" -print0 | \
+    xargs -0 -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
