fix

diff --git a/framework/Makefile b/framework/Makefile
--- a/framework/Makefile
+++ b/framework/Makefile
@@ -6,16 +6,16 @@ prove:
 	@cd move-stdlib && \
 	echo "Testing move-stdlib" && \
 	find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
-	xargs -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+	xargs -0 -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
 
 	@cd vendor-stdlib && \
 	echo "Testing vendor-stdlib" && \
 	find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
-	xargs -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+	xargs -0 -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
 
 	@cd libra-framework && \
 	echo "Testing libra-framework" && \
 	find . -type f -name "*.move" ! -name "*.spec.move" -print0 | \
 	awk -v RS='\0' -v ORS='\0' '{sub(/^\.\//,""); print}' | \
 	sort -uz | \
-	xargs -0 -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+	xargs -0 -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
