modify makefile for sub directories

diff --git a/framework/Makefile b/framework/Makefile
--- a/framework/Makefile
+++ b/framework/Makefile
@@ -13,7 +13,8 @@ prove:
 	find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
 	xargs -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
 
-	@cd libra-framework && \
-	echo "Testing libra-framework" && \
-	find . -type f -name "*.move" ! -name "*.spec.move" -print0 | \
-	xargs -0 -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
+    @cd libra-framework && \
+    echo "Testing libra-framework" && \
+    find . -type f -name "*.move" ! -name "*.spec.move" -print0 | \
+    sed 's|^\./||' | \
+    xargs -0 -I {} sh -c 'echo "Testing file: {}"; diem move prove -f {} || echo "Error in file: {}"'
