Move tests directly to ci

diff --git a/.github/workflows/formal.yaml b/.github/workflows/formal.yaml
--- a/.github/workflows/formal.yaml
+++ b/.github/workflows/formal.yaml
@@ -43,8 +43,25 @@ jobs:
           chmod +x ${{github.workspace}}/diem &&
           cp ${{github.workspace}}/diem ~/.cargo/bin
 
-      # Move framework tests
-      # TODO:
-      - name: prover tests
-        working-directory: ./framework
-        run: make prove
+      - name: Prover tests for move-stdlib
+        run: |
+          cd move-stdlib
+          echo "Testing move-stdlib"
+          find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
+          xargs -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
+
+      - name: Prover tests for vendor-stdlib
+        run: |
+          cd vendor-stdlib
+          echo "Testing vendor-stdlib"
+          find sources -type f -name "*.move" ! -name "*.spec.move" | sed 's/\.move$$//' | \
+          xargs -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
+
+      - name: Prover tests for libra-framework
+        run: |
+          cd libra-framework
+          echo "Testing libra-framework"
+          find . -type f -name "*.move" ! -name "*.spec.move" -print0 | \
+          awk -v RS='\0' -v ORS='\0' '{sub(/^\.\//,""); print}' | \
+          sort -uz | \
+          xargs -0 -I {} sh -c 'echo "Testing file: {}"; if ! diem move prove -f {} | grep -q "\"Result\": \"Success\""; then echo "Error in file: {}"; exit 1; fi'
